### ISSUE TITLE
Use dnd5e config to fetch condition names 

### ISSUE THREAD

**Issue by pgervais70** [thatlonelybugbear/automated-conditions-5e#1]
It would be more portable if instead of hardcoding the effect label values you used the labels from dnd5e conditions config, e.g. : CONFIG.DND5E.conditionTypes.restrained

**Comment by thatlonelybugbear** [comment]
Indeed! This is scheduled to be changed in the next release.

**Comment by thatlonelybugbear** [comment]
Changes in v10.0.1
