### ISSUE TITLE
[Enhancement] - Lack of armor proficiency restricts spell casting

### ISSUE THREAD

**Issue by thatlonelybugbear** [thatlonelybugbear/automated-conditions-5e#108]
Your class gives you proficiency with certain types of armor. If you wear armor that you lack proficiency with, you have:
- [X] disadvantage on any ability check, saving throw, or attack roll that involves Strength or Dexterity, 
- [ ] **and you can't cast spells.**
  - [ ] Option 1: Enforce use cancel
  - [ ] Option 2: Warn when needed

**Comment by maxobremer** [comment]
and yes this is indeed RAW
