### ISSUE TITLE
[Bug] Non-proficient with shields not being triggered

### ISSUE THREAD

**Issue by glitchies** [thatlonelybugbear/automated-conditions-5e#125]
Shields should have the same disadvantages as armor when it comes to non-proficiency.

> **Armor Proficiency.** Anyone can put on a suit of armor or strap a shield to an arm. Only those proficient in the armor's use know how to wear it effectively, however. Your class gives you proficiency with certain types of armor. If you wear armor that you lack proficiency with, you have disadvantage on any ability check, saving throw, or attack roll that involves Strength or Dexterity, and you can't cast spells.

Tested with different shields, and armor.  All armor worked as intended, no shields cause the disadvantage.

Shield Proficiency is obtained from Class Features, or the Moderately Armored feat.

Foundry - 11.315
DnD5e - 3.1.2

**Comment by thatlonelybugbear** [comment]
Good point. I haven't added Shields in the mix to be honest, cause I didn't think about it.

I will put it in the next release.
Thanks for that.
