### ISSUE TITLE
Monk Unarmored Defense - Applying Disadvantage.

### ISSUE THREAD

**Issue by RoseyNZ** [thatlonelybugbear/automated-conditions-5e#132]
HI,  I've tested over and over with all the characters I have.  

Only an issue with Monks, even if I remove unarmored defense, give them normal armor and it still gives disadvantage on dex abilities and saves, as well as attacks etc.  but if I turn off the AC Automation in this module, the problem is resolved.

Version: 11.315.310.1

**Comment by thatlonelybugbear** [comment]
Ok I will take a look. An interaction I didn't think about ahead of time.

Thanks for the issue report, it helps a lot!

**Comment by thatlonelybugbear** [comment]
If you update and you still have the issue, can you export the Actor that rolls with disadvantage and attach the file here?
I am trying to replicate, but I cannot on version 11.315312.7 of the module with the Starter hero Perrin who has Unarmored Defence on.

**Comment by thatlonelybugbear** [comment]
I will close this tentatively. If the issue persists in the latest version, please open again.
