### ISSUE TITLE
Foundry v12 and DnD5e 3.2 compatibility

### ISSUE THREAD

**Issue by unvrtz** [thatlonelybugbear/automated-conditions-5e#135]
With the new releases of Foundry and DnD5e system it would be nice to add module compatibility with them.

**Comment by thatlonelybugbear** [comment]
There is a test release out already for v12.

A proper release will be out soon.

**Comment by unvrtz** [comment]
I installed the version you mentioned, but every time I try to activate it in the module list and reload the game to apply changes, it gets deactivated. Am I doing something wrong?

**Comment by thatlonelybugbear** [comment]
Did you install manually using this one minifest URL?

<https://github.com/thatlonelybugbear/automated-conditions-5e/releases/download/v12.323320.1/module.json>

**Comment by unvrtz** [comment]
after a few updates and reinstalls it began to work. Thanks!

**Comment by thatlonelybugbear** [comment]
Closed by #136 

More work to follow. Report any issues in the git please :)
