### ISSUE TITLE
[Bug][V12] Exhaustion for Death Saves is always Enabled

### ISSUE THREAD

**Issue by maxobremer** [thatlonelybugbear/automated-conditions-5e#137]
When having the option AC5e exhaustion automation disabled, it still enforces disadvantage on death saves if exhaustion is high enough
![image](https://github.com/thatlonelybugbear/automated-conditions-5e/assets/86924581/cace98fc-e442-4eea-85ff-b126f0aee3a2)
Doesn't do it for other saves btw

Foundry v12.328
DnD5e 3.2.1
AC5e 11.315321.1

**Comment by thatlonelybugbear** [comment]
I will take a look. Are you rolling directly from the character sheet?

**Comment by thatlonelybugbear** [comment]
Fixed in v11.315321.2.

Thanks for the report :)
