### ISSUE TITLE
Update to V12?

### ISSUE THREAD

**Issue by Stormthirst** [thatlonelybugbear/automated-conditions-5e#141]
Will this module be updated to Foundry V12?

**Comment by thatlonelybugbear** [comment]
Already is. Try uninstalling and installing again if for some reason it doesn't take.

Which version are you on?

Latest: <https://github.com/thatlonelybugbear/automated-conditions-5e/releases/download/v11.315321.3/module.json>

**Comment by Stormthirst** [comment]
Oh ok - I am using the latest one, but on V12, it's showing a "compatibility risk".

**Comment by thatlonelybugbear** [comment]
Yeah that is correct, I haven't updated the verified version to v12.238, as I am changing some stuff around, which will probably mark the module v12 compatible only when I do.
