### ISSUE TITLE
[Feature request] Compatibility with 3.3.1

### ISSUE THREAD

**Issue by mcabel** [thatlonelybugbear/automated-conditions-5e#142]
Please, add compatibility with dnd version 3.3.1 on v11 315

**Comment by thatlonelybugbear** [comment]
As I am away for the weekend and I haven't tested 3.3.1 + AC5e extensively, I might create a prerelease version for anyone that wants to test it or needs it in the meantime.

**Comment by thatlonelybugbear** [comment]
Pre-release. 

Disclaimer: I haven't tested. Shouldnt be issues, but make a backup to be safe and let me know of any issues encountered.

<https://github.com/thatlonelybugbear/automated-conditions-5e/releases/download/v11.315331/module.json>

**Comment by thatlonelybugbear** [comment]
Closing with #146
