### ISSUE TITLE
Exhaustion Level 2 not calculating correctly

### ISSUE THREAD

**Issue by ravingdragoon** [thatlonelybugbear/automated-conditions-5e#148]
Hi, I noticed on my monk that Level 2 of exhaustion is not correctly halving the movement speed. It does not take into account the Unarmored Movement or Mobile feat bonuses to speed before halving the movement speed, leading to the system showing considerably more movement than I should have available.

**Comment by thatlonelybugbear** [comment]
Hey there. I am not doing anything to alter the system's way of halving movement.

The only thing that Automated Conditions 5e is affecting, is the advantageMode for saves.

Are you maybe using DFreds CE or some other such module, already halving the movement on the top of the 5e system's reduction?

**Comment by ravingdragoon** [comment]
> Hey there. I am not doing anything to alter the system's way of halving movement.
> 
> The only thing that Automated Conditions 5e is affecting, is the advantageMode for saves.
> 
> Are you maybe using DFreds CE or some other such module, already halving the movement on top of the 5e system's reduction?

I am using Midi-QOL and its requirements, but most automation isn't compatible with V12 or DnD3.3 yet, so I have things like DFreds CE and CPR disabled currently. I do apologize though, I thought your module was handling the exhaustion. 

The issue seems to be that whatever is halving movement is doing so before any bonuses to movement are applied, so the base walk speed of 30 is being halved to 15, then the +10 from mobile and +30 from unarmored defense are being added, resulting in the monk showing 55 feet of movement instead of the actual halved movement which should be 35.

**Comment by thatlonelybugbear** [comment]
No worries. I would suggest dropping by posney's discord and creating a troubleshooting-forum post with your Troubleshooter exported file attached.
We can take a closer look there ;)
