### ISSUE TITLE
Notification when rolling attacks or damage setting

### ISSUE THREAD

**Issue by maxobremer** [thatlonelybugbear/automated-conditions-5e#63]
the notification when rolling for attack or damage is not always desired, a setting to turn it off would be nice.
![image](https://github.com/thatlonelybugbear/automated-conditions-5e/assets/86924581/ca981ae6-6c19-460b-94ac-54178699d7e0)

**Comment by thatlonelybugbear** [comment]
Yes I was aware that it would have an impact, but wanted to at least make users aware that this is an issue. I will rethink that warning trigger and remove it probably in the next release.
