### ISSUE TITLE
Feature request: Option to Disable UI Notification Warnings

### ISSUE THREAD

**Issue by puddleimages** [thatlonelybugbear/automated-conditions-5e#65]
The warning notifications can be a bit much for some of my players depending on display size and frequency of attacks without a target selected.

**Comment by thatlonelybugbear** [comment]
Hey there, are you on latest version. 11.315.304.7 ?

If yes, these warnings should only be shown if you choose the `Enforce targeting` option in the module settings.

Can you confirm version and relevant option selected?

**Comment by puddleimages** [comment]
It looks like your most recent update resolved my concern. Sorry about that! Thanks for the module!

**Comment by thatlonelybugbear** [comment]
Glad to hear it's working as intended. Thanks!
