### ISSUE TITLE
[Feature Request] Disable encumbrance for Item Piles

### ISSUE THREAD

**Issue by FurtherV** [thatlonelybugbear/automated-conditions-5e#74]
Currently, some item pile tokens (from https://foundryvtt.com/packages/item-piles) that contain items which are pretty heavy gain the `Exceeding Carrying Capacity` effect. While "correct", this seems a bit non-sensical and actually also makes their images a tiny bit cluttered with the status effect icon.

**Comment by thatlonelybugbear** [comment]
I think that this is an issue which should be raised in Item Piles instead.

Automated conditions 5e do not add any status effects on Actors, but just use any such effects already present on them to calculate the advantageMode for relevant Rolls.

I will close this for now, but please do reopen if that doesn't make sense.
