### ISSUE TITLE
[BUG] Natural armor is considered as unproficient with the armor check setting on

### ISSUE THREAD

**Issue by FurtherV** [thatlonelybugbear/automated-conditions-5e#77]
When the AC5e armor automation setting is enabled, a creature that has only natural armor like the **Ogre Zombie** from the system's SRD, is considered unproficient with that armor and gets disadvantage on a attack rolls. 

I think this behavior is wrong and a bug, as per RAW a creature is always proficient with its natural armor.

**Comment by thatlonelybugbear** [comment]
I have already corrected this in the soon to be released version ( #72 )

Thanks for taking the time to write this up though! 👍

**Comment by thatlonelybugbear** [comment]
Still an issue in 11.315312.2.1
